"""initial schema

Revision ID: 62484e322cba
Revises:
Create Date: 2026-09-30 01:49:13.367172

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "62484e322cba"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "game_pregame",
        sa.Column("game_id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("p_home_reg", sa.Float(), nullable=False),
        sa.Column("p_away_reg", sa.Float(), nullable=False),
        sa.Column("p_home_ot", sa.Float(), nullable=False),
        sa.Column("p_away_ot", sa.Float(), nullable=False),
        sa.Column("p_home_so", sa.Float(), nullable=False),
        sa.Column("p_away_so", sa.Float(), nullable=False),
        sa.Column("exp_home_goals", sa.Float(), nullable=False),
        sa.Column("exp_away_goals", sa.Float(), nullable=False),
        sa.Column("model_version", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("game_id"),
    )
    op.create_table(
        "games",
        sa.Column("id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("season", sa.Integer(), nullable=False),
        sa.Column("game_type", sa.SmallInteger(), nullable=False),
        sa.Column("night_date", sa.Date(), nullable=False),
        sa.Column("start_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("home", sa.String(length=3), nullable=False),
        sa.Column("away", sa.String(length=3), nullable=False),
        sa.Column("venue", sa.String(length=96), nullable=True),
        sa.Column("neutral_site", sa.Boolean(), nullable=False),
        sa.Column("state", sa.String(length=8), nullable=False),
        sa.Column("schedule_state", sa.String(length=8), nullable=True),
        sa.Column("period", sa.SmallInteger(), nullable=True),
        sa.Column("period_type", sa.String(length=3), nullable=True),
        sa.Column("clock_seconds", sa.Integer(), nullable=True),
        sa.Column("in_intermission", sa.Boolean(), nullable=False),
        sa.Column("home_score", sa.SmallInteger(), nullable=True),
        sa.Column("away_score", sa.SmallInteger(), nullable=True),
        sa.Column("home_sog", sa.SmallInteger(), nullable=True),
        sa.Column("away_sog", sa.SmallInteger(), nullable=True),
        sa.Column("last_period_type", sa.String(length=3), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_games_away", "games", ["away"], unique=False)
    op.create_index("ix_games_home", "games", ["home"], unique=False)
    op.create_index(op.f("ix_games_night_date"), "games", ["night_date"], unique=False)
    op.create_index(op.f("ix_games_season"), "games", ["season"], unique=False)
    op.create_index("ix_games_season_type", "games", ["season", "game_type"], unique=False)
    op.create_index(op.f("ix_games_start_utc"), "games", ["start_utc"], unique=False)
    op.create_table(
        "ingest_cursors",
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "job_runs",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("job", sa.String(length=64), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_job_runs_job"), "job_runs", ["job"], unique=False)
    op.create_table(
        "players",
        sa.Column("id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("name", sa.String(length=96), nullable=False),
        sa.Column("position", sa.String(length=2), nullable=True),
        sa.Column("shoots_catches", sa.String(length=1), nullable=True),
        sa.Column("current_team", sa.String(length=3), nullable=True),
        sa.Column("sweater", sa.SmallInteger(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ratings",
        sa.Column("as_of_date", sa.Date(), nullable=False),
        sa.Column("team", sa.String(length=3), nullable=False),
        sa.Column("off", sa.Float(), nullable=False),
        sa.Column("def", sa.Float(), nullable=False),
        sa.Column("model_version", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("as_of_date", "team"),
    )
    op.create_table(
        "recaps",
        sa.Column("night_date", sa.Date(), nullable=False),
        sa.Column("headline", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("model", sa.String(length=64), nullable=False),
        sa.Column("validated", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("night_date"),
    )
    op.create_table(
        "reconcile_events",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "replay_bundles",
        sa.Column("night_date", sa.Date(), nullable=False),
        sa.Column("season", sa.Integer(), nullable=False),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("total_energy", sa.Float(), nullable=False),
        sa.Column("n_games", sa.SmallInteger(), nullable=False),
        sa.Column("n_tremors", sa.SmallInteger(), nullable=False),
        sa.Column(
            "built_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("night_date"),
    )
    op.create_index(op.f("ix_replay_bundles_season"), "replay_bundles", ["season"], unique=False)
    op.create_table(
        "shot_xg",
        sa.Column("game_id", sa.BigInteger(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("xg", sa.Float(), nullable=False),
        sa.Column("model_version", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("game_id", "event_id"),
    )
    op.create_table(
        "sim_runs",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("season", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("as_of", sa.DateTime(timezone=True), nullable=True),
        sa.Column("trigger", sa.String(length=24), nullable=False),
        sa.Column("trigger_ref", sa.String(length=64), nullable=True),
        sa.Column("n_sims", sa.Integer(), nullable=False),
        sa.Column("seed", sa.BigInteger(), nullable=False),
        sa.Column("state_hash", sa.String(length=64), nullable=False),
        sa.Column("duration_ms", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sim_runs_as_of"), "sim_runs", ["as_of"], unique=False)
    op.create_index(op.f("ix_sim_runs_season"), "sim_runs", ["season"], unique=False)
    op.create_table(
        "team_seasons",
        sa.Column("season", sa.Integer(), nullable=False),
        sa.Column("abbrev", sa.String(length=3), nullable=False),
        sa.Column("nhl_id", sa.Integer(), nullable=True),
        sa.Column("conference", sa.String(length=16), nullable=False),
        sa.Column("division", sa.String(length=16), nullable=False),
        sa.PrimaryKeyConstraint("season", "abbrev"),
    )
    op.create_table(
        "teams",
        sa.Column("abbrev", sa.String(length=3), nullable=False),
        sa.Column("nhl_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("conference", sa.String(length=16), nullable=False),
        sa.Column("division", sa.String(length=16), nullable=False),
        sa.Column("arena", sa.String(length=96), nullable=False),
        sa.Column("lat", sa.Float(), nullable=False),
        sa.Column("lon", sa.Float(), nullable=False),
        sa.Column("color_primary", sa.String(length=7), nullable=False),
        sa.Column("color_secondary", sa.String(length=7), nullable=False),
        sa.PrimaryKeyConstraint("abbrev"),
        sa.UniqueConstraint("nhl_id"),
    )
    op.create_table(
        "tremors",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("season", sa.Integer(), nullable=False),
        sa.Column("game_id", sa.BigInteger(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("team", sa.String(length=3), nullable=False),
        sa.Column("opponent", sa.String(length=3), nullable=False),
        sa.Column("scorer_id", sa.Integer(), nullable=True),
        sa.Column("assist1_id", sa.Integer(), nullable=True),
        sa.Column("assist2_id", sa.Integer(), nullable=True),
        sa.Column("goalie_id", sa.Integer(), nullable=True),
        sa.Column("period", sa.SmallInteger(), nullable=False),
        sa.Column("period_type", sa.String(length=3), nullable=False),
        sa.Column("t_period_s", sa.SmallInteger(), nullable=False),
        sa.Column("t_game_s", sa.Integer(), nullable=False),
        sa.Column("shootout", sa.Boolean(), nullable=False),
        sa.Column("score_before", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("score_after", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("wp_before", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("wp_after", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("deltas", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("total_shift", sa.Float(), nullable=False),
        sa.Column("magnitude", sa.Float(), nullable=False),
        sa.Column("ppa", sa.Float(), nullable=False),
        sa.Column("cpa", sa.Float(), nullable=False),
        sa.Column("origin_venue", sa.String(length=96), nullable=True),
        sa.Column("origin_lat", sa.Float(), nullable=True),
        sa.Column("origin_lon", sa.Float(), nullable=True),
        sa.Column("sim_run_before", sa.BigInteger(), nullable=True),
        sa.Column("sim_run_after", sa.BigInteger(), nullable=True),
        sa.Column("overturned", sa.Boolean(), nullable=False),
        sa.Column("night_date", sa.Date(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tremors_game_id"), "tremors", ["game_id"], unique=False)
    op.create_index(op.f("ix_tremors_magnitude"), "tremors", ["magnitude"], unique=False)
    op.create_index(op.f("ix_tremors_night_date"), "tremors", ["night_date"], unique=False)
    op.create_index("ix_tremors_season_mag", "tremors", ["season", "magnitude"], unique=False)
    op.create_index("ix_tremors_team", "tremors", ["team"], unique=False)
    op.create_index("uq_tremors_game_event", "tremors", ["game_id", "event_id"], unique=True)
    op.create_table(
        "venues",
        sa.Column("name", sa.String(length=96), nullable=False),
        sa.Column("city", sa.String(length=96), nullable=False),
        sa.Column("country", sa.String(length=2), nullable=False),
        sa.Column("lat", sa.Float(), nullable=False),
        sa.Column("lon", sa.Float(), nullable=False),
        sa.Column("home_team", sa.String(length=3), nullable=True),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "wp_timeline",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("game_id", sa.BigInteger(), nullable=False),
        sa.Column("t_game_s", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=True),
        sa.Column("p_home_reg", sa.Float(), nullable=False),
        sa.Column("p_away_reg", sa.Float(), nullable=False),
        sa.Column("p_home_ot", sa.Float(), nullable=False),
        sa.Column("p_away_ot", sa.Float(), nullable=False),
        sa.Column("p_home_so", sa.Float(), nullable=False),
        sa.Column("p_away_so", sa.Float(), nullable=False),
        sa.Column("model_version", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_wp_timeline_game_id"), "wp_timeline", ["game_id"], unique=False)
    op.create_table(
        "conditional_tables",
        sa.Column("sim_run_id", sa.BigInteger(), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(["sim_run_id"], ["sim_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("sim_run_id"),
    )
    op.create_table(
        "plays",
        sa.Column("game_id", sa.BigInteger(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("period", sa.SmallInteger(), nullable=False),
        sa.Column("period_type", sa.String(length=3), nullable=False),
        sa.Column("t_period_s", sa.SmallInteger(), nullable=False),
        sa.Column("t_game_s", sa.Integer(), nullable=False),
        sa.Column("situation_code", sa.String(length=4), nullable=True),
        sa.Column("type", sa.String(length=24), nullable=False),
        sa.Column("owner_team", sa.String(length=3), nullable=True),
        sa.Column("x", sa.Float(), nullable=True),
        sa.Column("y", sa.Float(), nullable=True),
        sa.Column("x_norm", sa.Float(), nullable=True),
        sa.Column("y_norm", sa.Float(), nullable=True),
        sa.Column("zone", sa.String(length=1), nullable=True),
        sa.Column("shot_type", sa.String(length=16), nullable=True),
        sa.Column("shooter_id", sa.Integer(), nullable=True),
        sa.Column("scorer_id", sa.Integer(), nullable=True),
        sa.Column("assist1_id", sa.Integer(), nullable=True),
        sa.Column("assist2_id", sa.Integer(), nullable=True),
        sa.Column("goalie_id", sa.Integer(), nullable=True),
        sa.Column("home_score", sa.SmallInteger(), nullable=True),
        sa.Column("away_score", sa.SmallInteger(), nullable=True),
        sa.Column("penalty_minutes", sa.SmallInteger(), nullable=True),
        sa.Column("raw", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("content_hash", sa.String(length=16), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["game_id"], ["games.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("game_id", "event_id"),
    )
    op.create_index("ix_plays_game_sort", "plays", ["game_id", "sort_order"], unique=False)
    op.create_index("ix_plays_scorer", "plays", ["scorer_id"], unique=False)
    op.create_index("ix_plays_type", "plays", ["type"], unique=False)
    op.create_table(
        "rooting_guides",
        sa.Column("sim_run_id", sa.BigInteger(), nullable=False),
        sa.Column("team", sa.String(length=3), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(["sim_run_id"], ["sim_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("sim_run_id", "team"),
    )
    op.create_table(
        "team_odds",
        sa.Column("sim_run_id", sa.BigInteger(), nullable=False),
        sa.Column("team", sa.String(length=3), nullable=False),
        sa.Column("p_playoffs", sa.Float(), nullable=False),
        sa.Column("p_division", sa.Float(), nullable=False),
        sa.Column("p_top3_div", sa.Float(), nullable=False),
        sa.Column("p_wildcard", sa.Float(), nullable=False),
        sa.Column("p_presidents", sa.Float(), nullable=False),
        sa.Column("p_conf_first", sa.Float(), nullable=False),
        sa.Column("p_round2", sa.Float(), nullable=False),
        sa.Column("p_conf_final", sa.Float(), nullable=False),
        sa.Column("p_final", sa.Float(), nullable=False),
        sa.Column("p_cup", sa.Float(), nullable=False),
        sa.Column("p_last", sa.Float(), nullable=False),
        sa.Column("exp_points", sa.Float(), nullable=False),
        sa.Column("points_hist", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("seed_dist", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(["sim_run_id"], ["sim_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("sim_run_id", "team"),
    )
    op.create_index("ix_team_odds_team", "team_odds", ["team"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_team_odds_team", table_name="team_odds")
    op.drop_table("team_odds")
    op.drop_table("rooting_guides")
    op.drop_index("ix_plays_type", table_name="plays")
    op.drop_index("ix_plays_scorer", table_name="plays")
    op.drop_index("ix_plays_game_sort", table_name="plays")
    op.drop_table("plays")
    op.drop_table("conditional_tables")
    op.drop_index(op.f("ix_wp_timeline_game_id"), table_name="wp_timeline")
    op.drop_table("wp_timeline")
    op.drop_table("venues")
    op.drop_index("uq_tremors_game_event", table_name="tremors")
    op.drop_index("ix_tremors_team", table_name="tremors")
    op.drop_index("ix_tremors_season_mag", table_name="tremors")
    op.drop_index(op.f("ix_tremors_night_date"), table_name="tremors")
    op.drop_index(op.f("ix_tremors_magnitude"), table_name="tremors")
    op.drop_index(op.f("ix_tremors_game_id"), table_name="tremors")
    op.drop_table("tremors")
    op.drop_table("teams")
    op.drop_table("team_seasons")
    op.drop_index(op.f("ix_sim_runs_season"), table_name="sim_runs")
    op.drop_index(op.f("ix_sim_runs_as_of"), table_name="sim_runs")
    op.drop_table("sim_runs")
    op.drop_table("shot_xg")
    op.drop_index(op.f("ix_replay_bundles_season"), table_name="replay_bundles")
    op.drop_table("replay_bundles")
    op.drop_table("reconcile_events")
    op.drop_table("recaps")
    op.drop_table("ratings")
    op.drop_table("players")
    op.drop_index(op.f("ix_job_runs_job"), table_name="job_runs")
    op.drop_table("job_runs")
    op.drop_table("ingest_cursors")
    op.drop_index(op.f("ix_games_start_utc"), table_name="games")
    op.drop_index("ix_games_season_type", table_name="games")
    op.drop_index(op.f("ix_games_season"), table_name="games")
    op.drop_index(op.f("ix_games_night_date"), table_name="games")
    op.drop_index("ix_games_home", table_name="games")
    op.drop_index("ix_games_away", table_name="games")
    op.drop_table("games")
    op.drop_table("game_pregame")
    # ### end Alembic commands ###
